Vendor.create!([
  {key: "C1", vendor_type: "vendor_food", status: "open", business_name: "Via Tevere Pizzeria", location: "C1 Authorised Parking Meter - West Side of 400 Burrard St", description: "Pizza", lat: 49.2869, lon: -123.118},
  {key: "C10", vendor_type: "vendor_food", status: "open", business_name: "Mum's Grilled Cheese Truck", location: "C10 Authorised Parking Meter -West Side of 700 Howe St", description: "Sandwiches and Soups", lat: 49.2822, lon: -123.121},
  {key: "C11", vendor_type: "vendor_food", status: "open", business_name: "Holy Perogy", location: nil, description: "Ukranian", lat: 49.2857, lon: -123.12},
  {key: "C12", vendor_type: "vendor_food", status: "open", business_name: "Ze Bite", location: "C12 Authorised Parking Meter - North Side of W Cordova St - East of Burrard St", description: "French Cuisine", lat: 49.2876, lon: -123.116},
  {key: "C13", vendor_type: "vendor_food", status: "open", business_name: "Pig on the Street", location: "C13 Authorised Parking Meter - West Side of 700 Howe St - Mid Block", description: "British Sandwiches", lat: 49.2824, lon: -123.12},
  {key: "C15", vendor_type: "vendor_food", status: "open", business_name: "Kaboom Box", location: "C15 Authorised Parking Meter - North Side of 1000 W Georgia St", description: "Seafood", lat: 49.2852, lon: -123.122},
  {key: "C17", vendor_type: "vendor_food", status: "open", business_name: "Le Tigre", location: "C17 Authorised Parking Meter - North Side of Alberni St - East of Bute St", description: "Chinese Cuisine", lat: 49.2866, lon: -123.126},
  {key: "C19", vendor_type: "vendor_food", status: "open", business_name: "The Reef", location: "C19 Authorised Parking Meter - East Side of Thurlow St - North of W Hastings St", description: "Caribbean", lat: 49.288, lon: -123.12},
  {key: "C20", vendor_type: "vendor_food", status: "pending", business_name: "Holy Perogy", location: "C20 Authorised Parking Meter - East Side of 700 Homer St - Mid Block", description: "Ukranian Cuisine", lat: 49.2799, lon: -123.116},
  {key: "C3", vendor_type: "vendor_food", status: "open", business_name: "Mr. Shawarma", location: "C3 Authorised Parking Meter - North Side of 1000 Melville St", description: "Philly Cheese Steak", lat: 49.2854, lon: -123.12},
  {key: "C4", vendor_type: "vendor_food", status: "open", business_name: "Tacofino", location: "C4 Authorised Parking Meter West Side 500 Burrard St", description: "Seafood", lat: 49.286, lon: -123.119},
  {key: "C5", vendor_type: "vendor_food", status: "open", business_name: "Tacofino", location: "C5 Authorised Parking Meter North West corner of Howe St and Robson St", description: "Tacos", lat: 49.2823, lon: -123.121},
  {key: "C6", vendor_type: "vendor_food", status: "open", business_name: "The Juice Truck", location: "C6 Authorised Parking Meter West Side of 200 block of Abbott St", description: "Juice and Smoothies", lat: 49.2837, lon: -123.107},
  {key: "C7", vendor_type: "vendor_food", status: "open", business_name: "Roaming Dragon", location: "C7 Authorised Parking Meter South East corner of Burrard St and Robson St", description: "Pan Asian", lat: 49.2831, lon: -123.123},
  {key: "C8", vendor_type: "vendor_food", status: "open", business_name: "Gourmet Syndicate", location: "C8 Authorised Parking Meter South East corner of Burrard St at Smithe St", description: "Comfort Food", lat: 49.2821, lon: -123.125},
  {key: "C9", vendor_type: "vendor_food", status: "open", business_name: "Feastro - The Rolling Bistro", location: "C9 Authorised Parking Meter - Thurlow St at W Cordova St", description: "Seafood", lat: 49.2887, lon: -123.118},
  {key: "DT01", vendor_type: "vendor_food", status: "open", business_name: nil, location: "East Side of 600 Beatty St - 6 Metres North of West Georgia St", description: "Hot Dogs", lat: 49.2787, lon: -123.112},
  {key: "DT02", vendor_type: "vendor_food", status: "open", business_name: "Yolk's", location: "East Side of 500 Beatty St - 6 Metres North of Dunsmuir St", description: "Breakfast Foods", lat: 49.2799, lon: -123.11},
  {key: "DT03", vendor_type: "vendor_food", status: "open", business_name: "YVS Nuts", location: "East Side of 500 Main St - 7 Metres South of E Pender St", description: "Chestnuts", lat: 49.2802, lon: -123.1},
  {key: "DT04", vendor_type: "vendor_food", status: "open", business_name: nil, location: "West Side of 600 Homer St - 6 Metres North of West Georgia St", description: "Hot Dogs", lat: 49.2808, lon: -123.115},
  {key: "DT08", vendor_type: "vendor_food", status: "open", business_name: "Soho Road Naan Kebab", location: "South Side of 800 Smithe St - 6 metres West of Howe St", description: "Indian Cuisine", lat: 49.281, lon: -123.123},
  {key: "DT10", vendor_type: "vendor_food", status: "open", business_name: nil, location: "Expo Boulevard - 20 Metres West of Abbott St", description: "Hot Dogs", lat: 49.2788, lon: -123.108},
  {key: "DT13", vendor_type: "vendor_food", status: "open", business_name: nil, location: "North Side of 900 Robson St - 6 Metres East of Burrard St", description: "Hot Dogs", lat: 49.2833, lon: -123.123},
  {key: "DT24", vendor_type: "vendor_food", status: "open", business_name: "Street Meet", location: "West Side of 500 Burrard St - Authorised Parking Meter", description: "Mediterranean", lat: 49.2865, lon: -123.118},
  {key: "SFV136", vendor_type: "vendor_food", status: "pending", business_name: "Eat Sexy", location: "Westside 400 Cambie St", description: "Healthy Fusion", lat: 49.2818, lon: -123.11},
  {key: "SFV137", vendor_type: "vendor_food", status: "open", business_name: "JJs Trucketeria", location: "Abbott and Expo St.", description: "Healthy Philippino Fusion", lat: 49.2785, lon: -123.108},
  {key: "SFV138", vendor_type: "vendor_food", status: "open", business_name: "Taqueria and Salsa Bar", location: "South Side of 1700 E Broadway", description: "Tacos and Fresh Salsas", lat: 49.2622, lon: -123.069},
  {key: "SFV139", vendor_type: "vendor_food", status: "open", business_name: "Bike Caffe", location: "Olympic Village Skytrain Station", description: "Sustainable Coffee and Gluten Free Baked Goods", lat: 49.2662, lon: -123.116},
  {key: "OD04", vendor_type: "vendor_food", status: "pending", business_name: "Falafel Plus", location: "West Side of 2700 Laurel St - South of W 10th Ave", description: "Israeli Kosher", lat: 49.2616, lon: -123.126},
  {key: "DT15", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 200 West Georgia St - 8 Metres East of Hamilton St", description: "Hot Dogs", lat: 49.2798, lon: -123.114},
  {key: "DT16", vendor_type: "vendor_food", status: "open", business_name: "Mogu", location: "West Side of Howe St - South of Dunsmuir St", description: "Japanese Cuisine", lat: 49.2842, lon: -123.118},
  {key: "DT17", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 600 West Georgia St - 6 Metres East of Granville St", description: "Hot Dogs", lat: 49.2823, lon: -123.118},
  {key: "DT19", vendor_type: "vendor_food", status: "open", business_name: "Japadog", location: "North Side of 600 West Cordova St - 6 Metres East of Granville St", description: "Hot Dogs", lat: 49.2859, lon: -123.112},
  {key: "DT21", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 300 Davie St - 6 Metres East of Hamilton St", description: "Hot Dogs", lat: 49.2747, lon: -123.123},
  {key: "DT22", vendor_type: "vendor_food", status: "open", business_name: "YVS Nuts", location: "North Side of 800 Robson St - 6 Metres West of Howe St", description: "Chestnuts", lat: 49.2821, lon: -123.121},
  {key: "DT23", vendor_type: "vendor_food", status: "pending", business_name: nil, location: "North Side of 1000 Robson St - 79 Metres West of Burrard St", description: "Hot Dogs", lat: 49.2839, lon: -123.124},
  {key: "DT26", vendor_type: "vendor_food", status: "open", business_name: "Japadog", location: "East Side of 500 Burrard St - 6 Metres South of West Pender St", description: "Hot Dogs", lat: 49.2864, lon: -123.118},
  {key: "DT28", vendor_type: "vendor_food", status: "open", business_name: "Vij's Railway Express", location: "North Side of 1000 West Georgia St - East of Thurlow St", description: "Indian", lat: 49.2856, lon: -123.123},
  {key: "DT31", vendor_type: "vendor_food", status: "open", business_name: "Japadog", location: "West Side of 500 Granville St - 10 Metres South of West Pender St", description: "Hot Dogs", lat: 49.2845, lon: -123.115},
  {key: "DT32", vendor_type: "vendor_food", status: "open", business_name: "Tikka Dog", location: "North Side of 500 W Cordova St - 59 Metres West of Richards St", description: "Hot Dogs", lat: 49.2852, lon: -123.111},
  {key: "DT35", vendor_type: "vendor_food", status: "open", business_name: nil, location: "West Side of 1100 Burrard St - 10 Metres North of Davie St", description: "Hot Dogs", lat: 49.2793, lon: -123.129},
  {key: "DT37", vendor_type: "vendor_food", status: "open", business_name: nil, location: "West Side of 700 Burrard St - 15 Metres North of Robson St", description: "Hot Dogs", lat: 49.2835, lon: -123.123},
  {key: "DT38", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 800 W Georgia St - 55 Metres West of Howe St", description: "Hot Dogs", lat: 49.2835, lon: -123.12},
  {key: "DT39", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 800 Robson St  -12 Metres West of Howe St", description: "Hot Dogs", lat: 49.2823, lon: -123.121},
  {key: "DT40", vendor_type: "vendor_food", status: "open", business_name: "Cazba Express", location: "North Side of 700 Robson St - 12 Metres West of Granville St", description: "Persian Cuisine", lat: 49.2815, lon: -123.12},
  {key: "DT41", vendor_type: "vendor_food", status: "open", business_name: "Van Dog", location: "South Side of 900 Robson St - 6 Metres East of Burrard St", description: "Hot Dogs", lat: 49.2831, lon: -123.123},
  {key: "DT42", vendor_type: "vendor_food", status: "open", business_name: "The Burger Bus", location: "South Side of 900 Robson St - 16 Metres West of Hornby St", description: "Burgers and Hot Dogs", lat: 49.2828, lon: -123.122},
  {key: "DT45", vendor_type: "vendor_food", status: "pending", business_name: nil, location: "Foot of Davie St - 2 Metres South of Marinaside Cres.", description: "Hot Dogs", lat: 49.2729, lon: -123.12},
  {key: "DT46", vendor_type: "vendor_food", status: "open", business_name: "Super Baguette", location: "North Side of 900 Robson St  - 9 Metres West of Hornby St", description: "Sandwiches", lat: 49.2828, lon: -123.122},
  {key: "DT47", vendor_type: "vendor_food", status: "open", business_name: "Street Hots", location: "North Side of Davie St - East of Seymour St", description: "Hot Dogs and Burgers", lat: 49.2763, lon: -123.125},
  {key: "DT48", vendor_type: "vendor_food", status: "open", business_name: nil, location: "East Side of 800 Beatty St - 6 Metres South of Robson St", description: "Hot Dogs", lat: 49.2774, lon: -123.114},
  {key: "DT49", vendor_type: "vendor_food", status: "open", business_name: "Eat Chicken Wraps", location: "North Side of 700 Robson St - 49 Metres West of Granville St", description: "Wraps and Sandwiches", lat: 49.2818, lon: -123.12},
  {key: "DT50", vendor_type: "vendor_food", status: "open", business_name: nil, location: "East Side of 300 Thurlow St - 10 Metres North of West Hastings St", description: "Hot Dogs", lat: 49.2881, lon: -123.119},
  {key: "DT51", vendor_type: "vendor_food", status: "open", business_name: "Roaming Dragon", location: "North Side of 1000 W Georgia St - East of Thurlow St", description: "Pan Asian", lat: 49.2856, lon: -123.123},
  {key: "DT52", vendor_type: "vendor_food", status: "open", business_name: "Japadog", location: "West Side of 800 Burrard St - 2.5 Metres North of Smithe St", description: "Hot Dogs", lat: 49.2824, lon: -123.124},
  {key: "DT53", vendor_type: "vendor_food", status: "open", business_name: "Aussie Pie Guy", location: "East Side of 600 Hamilton St", description: "Australian Pies", lat: 49.2803, lon: -123.114},
  {key: "DT54", vendor_type: "vendor_food", status: "open", business_name: "Dim Sum Express", location: "East Side of 200 Howe St - 100 metres North of W Cordova St", description: "Dim Sum", lat: 49.2872, lon: -123.113},
  {key: "DT55", vendor_type: "vendor_food", status: "open", business_name: "Ursu Korean BBQ", location: "South Side of 400 W Georgia St - 12 metres East of Richards St", description: "Tacos", lat: 49.281, lon: -123.116},
  {key: "DT56", vendor_type: "vendor_food", status: "open", business_name: "Sea Dogs", location: "Coal Harbour Seawall  - 200 Metres Northeast of Broughton St", description: "Hot Dogs", lat: 49.2911, lon: -123.124},
  {key: "DT57", vendor_type: "vendor_food", status: "open", business_name: "Arturo's Mexico To Go", location: "North Side of 700 W Cordova St - 14 metres East of Howe St", description: "Mexican Cuisine", lat: 49.2865, lon: -123.114},
  {key: "DT59", vendor_type: "vendor_food", status: "open", business_name: "Re-Up BBQ", location: "East Side of 700 Hornby St - 22 metres South of W Georgia St", description: "Pulled Pork", lat: 49.2835, lon: -123.12},
  {key: "DT60", vendor_type: "vendor_food", status: "pending", business_name: nil, location: "South Side of 700 W Georgia St - 20 metres West of Granville St", description: nil, lat: 49.2825, lon: -123.118},
  {key: "DT61", vendor_type: "vendor_food", status: "open", business_name: "Fresh Local Wild", location: "South Side of 900 W Hastings St - 10 metres East of Burrard St", description: "Seafood", lat: 49.2869, lon: -123.117},
  {key: "DT63", vendor_type: "vendor_food", status: "open", business_name: "It's all About Grill", location: "West Side of 1100 Burrard St 10 metres North of Davie St", description: "BBQ", lat: 49.2794, lon: -123.129},
  {key: "DT64", vendor_type: "vendor_food", status: "open", business_name: "Mangali Kiss", location: "South Side of 800 W Georgia St - 30 metres West of Howe St", description: "Middle Eastern Cuisine", lat: 49.2833, lon: -123.12},
  {key: "DT70", vendor_type: "vendor_food", status: "pending", business_name: "Soho Road Naan Kebab", location: "South West Corner of Hornby St and Dunsmuir St", description: "Indian Cuisine", lat: 49.2849, lon: -123.119},
  {key: "DT71", vendor_type: "vendor_food", status: "open", business_name: "Didi's Greek", location: "South  Side of 1700 Robson St - 10 metres East of Denman St", description: "Greek Cuisine", lat: 49.2912, lon: -123.135},
  {key: "DT72", vendor_type: "vendor_food", status: "open", business_name: "The Hut", location: "East Side of 1200 Pacific Boulevard - 10 metres South of Davie St", description: "Vegan and Vegetarian", lat: 49.2738, lon: -123.122},
  {key: "DT74", vendor_type: "vendor_food", status: "open", business_name: "Re-Up BBQ", location: "South Side of 800 Robson St- 38 metres East of Hornby St", description: "BBQ", lat: 49.2823, lon: -123.121},
  {key: "DT75", vendor_type: "vendor_food", status: "open", business_name: "Finest at Sea", location: "South Side of 800 Robson St  - 28 metres East of Hornby St", description: "Seafood", lat: 49.2824, lon: -123.121},
  {key: "EB01", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 1800 Beach Ave  - 91 Metres West of Denman St", description: "Ice Cream", lat: 49.2876, lon: -123.143},
  {key: "EB02", vendor_type: "vendor_food", status: "open", business_name: "YVS Nuts", location: "South Side of 1800 Beach Ave  - 27 Metres West of Denman St", description: "Chestnuts", lat: 49.2871, lon: -123.142},
  {key: "EB03", vendor_type: "vendor_food", status: "open", business_name: "Lemon Sea", location: "South Side of 2000 Beach Av - 30 metres West of Chilco St", description: "Lemonade and Crepes", lat: 49.2897, lon: -123.145},
  {key: "EB04", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 1700 Beach Ave - East Side of Bidwell St", description: "Hot Dogs", lat: 49.2845, lon: -123.143},
  {key: "EB05", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 1900 Beach Ave - 29 Metres West of Gilford St", description: "Hot Dogs", lat: 49.2887, lon: -123.143},
  {key: "EB07", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 1800 Beach Ave - 95 Metres West of Denman St", description: "Hot Dogs", lat: 49.2876, lon: -123.143},
  {key: "GM02", vendor_type: "vendor_food", status: "open", business_name: "Big Dogs Hot Eats", location: "East Side of 600 Granville St - 73 Metres North of West Georgia St", description: "Hot Dogs", lat: 49.283, lon: -123.117},
  {key: "GM04", vendor_type: "vendor_food", status: "open", business_name: "Meals United Foods and Juices", location: "East Side of 600 Granville St - 65 Metres North of West Georgia St", description: "Sandwiches and Juices", lat: 49.2829, lon: -123.117},
  {key: "GM05", vendor_type: "vendor_food", status: "open", business_name: "Van Dog", location: "East Side of 800 Granville St - 30 Metres North of Smithe St", description: "Hot Dogs", lat: 49.2805, lon: -123.121},
  {key: "GM11", vendor_type: "vendor_food", status: "open", business_name: "Van Dog", location: "East Side of 900 Granville St - 75 Metres South of Smithe St", description: "Hot Dogs", lat: 49.2797, lon: -123.122},
  {key: "GM13", vendor_type: "vendor_food", status: "open", business_name: "Kaboom Box", location: "West Side of 700 Granville St - 36 Metres North of Robson St", description: "Seafood", lat: 49.2824, lon: -123.119},
  {key: "GM17", vendor_type: "vendor_food", status: "open", business_name: "Emelles Westside Wheels", location: "East Side of 500 Granville St - 10 Metres North of Dunsmuir St", description: "Sandwiches", lat: 49.2838, lon: -123.116},
  {key: "GM18", vendor_type: "vendor_food", status: "open", business_name: nil, location: "West Side of 700 Granville St - 6 Metres South of West Georgia St", description: "Hot Dogs", lat: 49.2825, lon: -123.118},
  {key: "GM20", vendor_type: "vendor_food", status: "open", business_name: "Nu Greek", location: "East Side of 600 Granville St - 20 Metres North of W Georgia St", description: "Greek Cuisine", lat: 49.2828, lon: -123.117},
  {key: "GM21", vendor_type: "vendor_food", status: "open", business_name: "Soho Road Naan Kebab", location: "South Side of 700 W Georgia St - West of Granville St", description: "Indian", lat: 49.2826, lon: -123.118},
  {key: "GT07", vendor_type: "vendor_food", status: "open", business_name: nil, location: "North Side of 300 Water St - 17 Metres West of Cambie St", description: "Hot Dogs", lat: 49.2844, lon: -123.109},
  {key: "GTBIA1", vendor_type: "vendor_food", status: "open", business_name: nil, location: "North Side of 100 Water St  - West of Abbott St", description: "Hot Dogs", lat: 49.284, lon: -123.107},
  {key: "OD03", vendor_type: "vendor_food", status: "pending", business_name: nil, location: "South Side 1500 West Broadway - West of Granville St", description: nil, lat: 49.2635, lon: -123.139},
  {key: "OD05", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 1700 East Broadway - 37 Metres East of Commercial Dr", description: "Hot Dogs", lat: 49.2622, lon: -123.069},
  {key: "OD08", vendor_type: "vendor_food", status: "open", business_name: nil, location: "North Side 100 Terminal Ave - 6 Metres West of Main St", description: "Hot Dogs", lat: 49.273, lon: -123.1},
  {key: "OD09", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 1100 West Broadway - East of Alder St", description: "Hot Dogs", lat: 49.2634, lon: -123.13},
  {key: "OD10", vendor_type: "vendor_food", status: "open", business_name: nil, location: "South Side of 1700 West Broadway - 40 Metres West of Pine St", description: "Hot Dogs", lat: 49.2636, lon: -123.144},
  {key: "OD12", vendor_type: "vendor_food", status: "open", business_name: nil, location: "East Side of 2200 Cambie St - 35 Metres South of W 6th Ave", description: "Hot Dogs", lat: 49.2653, lon: -123.115},
  {key: "OD14", vendor_type: "vendor_food", status: "pending", business_name: nil, location: "North Side of 600 W Broadway - 85 Metres West of Ash St", description: "Hot Dogs", lat: 49.2634, lon: -123.119},
  {key: "OD16", vendor_type: "vendor_food", status: "open", business_name: "Fasttrac Fusion", location: "East Side of 6400 Cambie St - 20 metres North of W 49th Ave", description: "Asian Fusion", lat: 49.2264, lon: -123.116},
  {key: "OD17", vendor_type: "vendor_food", status: "open", business_name: "Num Num", location: "South Side of 1500 W 10th Ave - Authorised Parking Meter", description: "Vietnamese", lat: 49.2626, lon: -123.139},
  {key: "OD18", vendor_type: "vendor_food", status: "open", business_name: nil, location: "West Side of 2900 Main St - 20 Metres North of E 14th Ave", description: "Hot Dogs", lat: 49.2585, lon: -123.102},
  {key: "OD19", vendor_type: "vendor_food", status: "open", business_name: "Taser Sandwiches", location: "East side of 1300 Main St - 10 metres North of Terminal Ave", description: "Sandwiches", lat: 49.273, lon: -123.1},
  {key: "OD20", vendor_type: "vendor_food", status: "pending", business_name: nil, location: "West Side of 1700 Anderson St - 20 Metres North of W 2nd Ave", description: nil, lat: 49.2696, lon: -123.138},
  {key: "RSBIA1", vendor_type: "vendor_food", status: "open", business_name: "YVS Nuts", location: "South Side of 1000 Robson Street - 7 Metres East of Thurlow Street", description: "Chestnuts", lat: 49.2844, lon: -123.125},
  {key: "SFV140", vendor_type: "vendor_food", status: "open", business_name: "San Juan Family Farm", location: "1800 Davie Street", description: "Fruit Shakes,  Smoothies and Juices", lat: 49.2877, lon: -123.142},
  {key: "SFV142", vendor_type: "vendor_food", status: "open", business_name: "Super Thai", location: "Eastside 1300 Pacific Boulevard", description: "Thai Food", lat: 49.2729, lon: -123.126},
  {key: "C16", vendor_type: "vendor_food", status: "open", business_name: "Feastro The Rolling Bistro", location: "Authorised Parking Location - West Side of 700 Howe St", description: "West Coast Fare", lat: 49.2824, lon: -123.12},
  {key: "DT58", vendor_type: "vendor_food", status: "open", business_name: "Mr. Shawarma", location: "North Side of 800 Robson St - East of Hornby St", description: "Middle Eastern", lat: 49.2826, lon: -123.121},
  {key: "C14", vendor_type: "vendor_food", status: "open", business_name: "Guanaco Truck", location: "Authroised Parking Meter - East Side of 800 Seymour St", description: "El Salvadorian Cuisine", lat: 49.2806, lon: -123.119},
  {key: "DT73", vendor_type: "vendor_food", status: "open", business_name: "Reel Mac and Cheese", location: "East Side of 600 Hamilton St", description: "Homemade Macaroni and Cheese", lat: 49.2803, lon: -123.114},
  {key: "DT67", vendor_type: "vendor_food", status: "open", business_name: "Dougie Luv Diner Truck", location: "East Side of 600 Hamilton St", description: "Diner Food", lat: 49.2804, lon: -123.113},
  {key: "DT66", vendor_type: "vendor_food", status: "open", business_name: "Patisserie Lebeau", location: "West Side of 700 Hamilton St", description: "Belgian Waffles", lat: 49.2799, lon: -123.115},
  {key: "DT77", vendor_type: "vendor_food", status: "open", business_name: "Fat Duck Mobile Eatery", location: "East Side of 600 Hamilton St", description: "Comfort Foods", lat: 49.2805, lon: -123.113},
  {key: "DT65", vendor_type: "vendor_food", status: "open", business_name: "Culver City Salads", location: "East Side of 600 Hamilton St", description: "Salads", lat: 49.2804, lon: -123.113},
  {key: "DT78", vendor_type: "vendor_food", status: "open", business_name: "Chou Chou Crepes", location: "East Side of 600 Hamilton St", description: "French Crepes", lat: 49.2801, lon: -123.114}
])
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
User.create!(name:  "Example User",
             email: "example@railstutorial.org",
             password:              "foobar",
             password_confirmation: "foobar",
             admin: true,
             activated: true,
             activated_at: Time.zone.now)

99.times do |n|
  name  = Faker::Name.name
  email = "example-#{n+1}@railstutorial.org"
  password = "password"
  User.create!(name:  name,
               email: email,
               password:              password,
               password_confirmation: password,
               activated: true,
               activated_at: Time.zone.now)
end

users = User.order(:created_at).take(6)
vendor_number = 1
50.times do
  content = Faker::Lorem.sentence(5)
  vendor = Vendor.find(vendor_number)
  vendor_number = vendor_number + 1
  users.each { |user| user.comments.create!(content: content, vendor_id: vendor.id) }
end
